Type ignore arg-type on command decorators
The upgrade to mypy 1.0 cause all functions decorated by
app_commands.command to raise an arg-type error (formatted for
readability):

threepseat/ext/birthdays/commands.py:189: error:
Argument 1 has incompatible type:
    Callable[
        [BirthdayCommands, Interaction, Member],
        Coroutine[Any, Any, None],
    ]
Expected:
    Union[
        Callable[
            [<nothing>, Interaction, VarArg(<nothing>), KwArg(<nothing>)],
            Coroutine[Any, Any, <nothing>],
        ],
        Callable[
            [Interaction, VarArg(<nothing>), KwArg(<nothing>)],
            Coroutine[Any, Any, <nothing>],
        ],
    ]

It looks like these should match but the <nothing> or VarArg(<nothing>)
are throwing mypy off so I've just type: ignored everything.